name: Update NPM packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update-packages:
    name: Update packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Update packages
        run: npx npm-check-updates -u && npm install

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: auroradysis@gmail.com
          author_name: Zhen Zhong
          message: "chore: update packages"
